### ISSUE TITLE
AttributeError: module 'glm' has no attribute 'ivec3'

### ISSUE THREAD

**Issue by happyleibniz** [obiwac/python-minecraft-clone#102]
first:
```console
pip install glm
```
then
```log
Traceback (most recent call last):
  File "C:\Users\Spinoza\python-minecraft-clone\community\main.py", line 17, in <module>
    import player
  File "C:\Users\Spinoza\python-minecraft-clone\community\player.py", line 5, in <module>
    import chunk
  File "C:\Users\Spinoza\python-minecraft-clone\community\chunk.py", line 6, in <module>
    import subchunk
  File "C:\Users\Spinoza\python-minecraft-clone\community\subchunk.py", line 1, in <module>
    from util import *
  File "C:\Users\Spinoza\python-minecraft-clone\community\util.py", line 3, in <module>
    DIRECTIONS = (glm.ivec3(1, 0, 0),
AttributeError: module 'glm' has no attribute 'ivec3'
```

(new.computer here)

**Comment by happyleibniz** [comment]
to install:
1.
do pip install pyglm
2.
pip uninstall glm
Then
pip install pyglm

**Comment by obiwac** [comment]
what's the issue here?

**Comment by happyleibniz** [comment]
nothing:)
sorry:))))
just some noobs typed pip install glm instead of pip install pyglm
________________________________

**Comment by happyleibniz** [comment]
nothing:)
sorry:))))
just some noobs typed pip install glm instead of pip install pyglm
