### ISSUE TITLE
Shader error

### ISSUE THREAD

**Issue by xing1357** [obiwac/python-minecraft-clone#22]
I am getting a error here:
Traceback (most recent call last):
  File "C:\Users\xingh\Downloads\python-minecraft-clone-master\python-minecraft-clone-master\episode-3\main.py", line 87, in <module>
    game = Game()
  File "C:\Users\xingh\Downloads\python-minecraft-clone-master\python-minecraft-clone-master\episode-3\main.py", line 81, in __init__
    self.window = Window(config = self.config, width = 800, height = 600, caption = "Minecraft clone", resizable = True, vsync = False)
  File "C:\Users\xingh\Downloads\python-minecraft-clone-master\python-minecraft-clone-master\episode-3\main.py", line 61, in __init__
    self.shader = shader.Shader("vert.glsl", "frag.glsl")
  File "C:\Users\xingh\Downloads\python-minecraft-clone-master\python-minecraft-clone-master\episode-3\shader.py", line 46, in __init__
    create_shader(self.vert_shader, vert_path)
  File "C:\Users\xingh\Downloads\python-minecraft-clone-master\python-minecraft-clone-master\episode-3\shader.py", line 37, in create_shader
    raise Shader_error(str(log_buffer.value))
shader.Shader_error: b''

**Comment by obiwac** [comment]
Thank you. Could you provide the vendor and model of your CPU? This is a problem a few people have been having and I haven't yet been able to reproduce it.

In the meantime, you can simply remove the error raising code.

**Comment by xing1357** [comment]
I was using a intel Core i5 vpro 2.3 ghz.

**Comment by obiwac** [comment]
Ok, does it work without the error handling code for you or not? I'll try to sort out that bug asap

**Comment by drakeerv** [comment]
I think I had the error earlier and I made a temporary fix for it by deleting the raise line for the error. The permanent fix would be replacing that with:
`
if log_length and log_buffer.value:
		raise Shader_error(str(log_buffer.value))
`

**Comment by drakeerv** [comment]
https://github.com/obiwac/python-minecraft-clone/pull/25

**Comment by obiwac** [comment]
Ok, when `log_buffer.value` evaluated to false, what's the value of `log_length`?

**Comment by drakeerv** [comment]
I think it might be c_int(-1) but I need to check.

**Comment by obiwac** [comment]
Then it may be smarter to instead check if `log_length > 0`.

**Comment by drakeerv** [comment]
I will try that.

**Comment by drakeerv** [comment]
It outputs c_long(1)

**Comment by drakeerv** [comment]
#26

**Comment by obiwac** [comment]
All is fixed! Thanks @drakeerv mate!
