### ISSUE TITLE
The window opens and closes quickly

### ISSUE THREAD

**Issue by aniketm32012** [obiwac/python-minecraft-clone#85]
`Traceback (most recent call last):
  File "C:\Users\Anike\OneDrive\Desktop\Lionrun\2023\CubeCrafter\main.py", line 149, in <module>
    game = Game()
  File "C:\Users\Anike\OneDrive\Desktop\Lionrun\2023\CubeCrafter\main.py", line 143, in __init__
    self.window = Window(config = self.config, width = 800, height = 600, caption = "Minecraft clone", resizable = True, vsync = False)
  File "C:\Users\Anike\OneDrive\Desktop\Lionrun\2023\CubeCrafter\main.py", line 25, in __init__
    self.cobblestone = block_type.Block_type(self.texture_manager, "cobblestone", {"all": "cobblestone"})
  File "C:\Users\Anike\OneDrive\Desktop\Lionrun\2023\CubeCrafter\block_type.py", line 12, in __init__
    texture_manager.add_texture(texture)
  File "C:\Users\Anike\OneDrive\Desktop\Lionrun\2023\CubeCrafter\texture_manager.py", line 40, in add_texture
    gl.glTexImage3D(glglTexImage3dargument)
TypeError: this function takes 10 arguments (1 given)`

**Comment by obiwac** [comment]
That code doesn't seem to be part of this Minecraft clone, sorry.
